import type { Metadata } from 'next';
import './globals.css';
import { inter } from './components/ui/fonts';
import { ThemeProvider } from './components/ui/theme-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased w-auto h-screen m-auto md:px-4 2xl:w-3/4`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="flex flex-col content-between justify-between">{children} </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
