import type { Metadata } from 'next';
import './globals.css';
import { inter } from './components/ui/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="w-3/4 h-screen m-auto">
        <main
          className={`${inter.className} antialiased flex flex-col content-between justify-between`}
        >
          {children}{' '}
        </main>
      </body>
    </html>
  );
}
